---
apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Network
metadata:
  name: vpc
  namespace: crossplane-system
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingConfig:
      routingMode: REGIONAL
  reclaimPolicy: Delete
  providerConfigRef:
    name: gcp-provider-config